[[ITKIOWrapper]]
arch = "aarch64"
git-tree-sha1 = "e219a936bf96ed54bf0ccc27fcd461786b1a9efd"
julia_version = "1.10.0"
os = "macos"

    [[ITKIOWrapper.download]]
    sha256 = "6a4d8d71996c3480b3c934fab750d2a51f231c4941348f3d02b5fb66dc322046"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
git-tree-sha1 = "1c74c9382fbd72e41c4367e6e12968ae01db0840"
julia_version = "1.11.1"
os = "macos"

    [[ITKIOWrapper.download]]
    sha256 = "811e9d9021a9a3c277962a5a16045906a764c0fe4c1907d02cba078531ae1c06"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
git-tree-sha1 = "0f624aab07cdf5b899eb500520dfc7cc10481c8e"
julia_version = "1.12.0"
os = "macos"

    [[ITKIOWrapper.download]]
    sha256 = "c46d87a946c81dfce5e91b6a616525a02b6bbd1098b8ce7d0241f688fe452be9"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
git-tree-sha1 = "a95bc1656f73856dd2cdd0ca423d4d4abc5291a1"
julia_version = "1.13.0"
os = "macos"

    [[ITKIOWrapper.download]]
    sha256 = "3ce2ddc08da78852d4fb23e557c24e1d99c677a8147eb1c838567d9a56a05d80"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5643925c2c1f42536ad5d26ce9c0b020c3df761f"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "f07363851f639120efac1aef9feada64cf99f2bd919aea482d60befc1982c80f"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "221f5e5d1c750a82c000a69d7c17a0ec11d66452"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "b1f374edc041dcaa873ef2d96fd99fe9563d0fb52346e1503e585f2fd99eb703"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb213a57598c911b1f513a3ed621ffbf3add8c7e"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "59b9a58fa84b3221581c9ebaa1acfa51ed70580c399404d3fb672d4d96addde6"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-gnu-cxx03-julia_version+1.12.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2477aaa7a549b69a7a8072c1f9697f7ecb6ddd4d"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "545b23c9463874a50d95d5cd84e5487bfc4a91551c847ef0da988281b948866f"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-gnu-cxx03-julia_version+1.13.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8b1b8bd19f344c37191d57b7a0d9cb95c1369d8"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "63e77b25aa90e3a6f337bcbf899f1c7da1dcddabf8323751752a47ab9481db74"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8980800a51c8d70b1e8821937332d21827a939c4"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "3eea6aae9175da0673e3f7eb9fb2bddd19a652a21e45db44b245933270a20ec9"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b30e31edd977d906ab3b20e77638e55b826fb636"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "f32b7960814505bf29a6fb816c5a7c4d526183b2cfcf26b0d36e646a02826f78"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e3a36a75af4023a32f3daf032769c04b6be3bac"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "af152e60f006de10d73038921dbd590a7276a9100accc1ec263108d1432aef08"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05f00446d84bc93dfc019cbec5243e92b60ef740"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "07dc2d51fd9a446d7198301a3be3a358cb2bfc9a476f798e78c3f97d83faf790"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-musl-cxx03-julia_version+1.10.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "827ce899dd2de247164a480bcf77c58e7917ed69"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "388b63ed68e21d8d1c6a4f84dbd6ef9b9d44b65555d8865e153219c5671b492a"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-musl-cxx03-julia_version+1.11.1.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f57facf1868e291b68f6fca97c64a3ea0ad98b55"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "7e67bba9321547daf8098c872f157a0c060f187894cf897877a31abd1d09a93d"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-musl-cxx03-julia_version+1.12.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1602c388cd1ff7dfd8c02cf9209d9948d9c5737a"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "3635809dcee507f4ee3ff5a369813cef0bb7259fec32d7e37e3308749155f9ac"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-musl-cxx03-julia_version+1.13.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5531cacfe9c732c7f4e11fb4488fd2d258e27d59"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "63112d9021e5373f315c34c1137fe0501325d8762ae511fcd3a1a1145fba93e5"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-musl-cxx11-julia_version+1.10.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a46f14472ba03ed2177f063d724e2e2f6c65a778"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "42bc1c6f1891d4fce5c3ae59465647f16ec6ed20ed31e873967805b12989ab53"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-musl-cxx11-julia_version+1.11.1.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f5c7d5e9ad6c2447b8ad866dd283a041ef332af"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "c9290276b38e84f058af3a3cefd9a4ebe1f36c28896d9d60d323705b9203f865"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[ITKIOWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95f4a8139967a3caa1287c060d0c8b17c0267539"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "893e1511934e38a77eb47086f35b84afb27c30c5d18320d3ae61b7c062aaacd3"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.aarch64-linux-musl-cxx11-julia_version+1.13.0.tar.gz"
[[ITKIOWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bdf776d74ff0de35d5316501774bb2673bcd785"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "abdea41cc8829e3056f30f760cf81f0ea6772f3e90aa4ee1d5e7df45ec73c5da"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.powerpc64le-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ITKIOWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15495f06b8ee01511f843477ae81e480004251c0"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "79cf816d62a534e2918df8f1e2ae2e71c402c3ffb5b6333bf31c40a46400a420"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.powerpc64le-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[ITKIOWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d3cb3a685fce8ee74e9865ae733223741f49e37"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "bbd2ac1c26de01b8e18a9486c01473041b09b6efa6135353bf611bb7a24a452f"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.powerpc64le-linux-gnu-cxx03-julia_version+1.12.0.tar.gz"
[[ITKIOWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9c844ffd3b3767490c695587fdd6290437a4bcf"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "705bbd4488330f067d863e40f0d94ca39b118bb687e808400d3b299c5cf61123"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.powerpc64le-linux-gnu-cxx03-julia_version+1.13.0.tar.gz"
[[ITKIOWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49a7931d8f93e8f7db6e69cbdb62edb7e4439963"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "31696d201e7d472dd53f0df834ad4463052d4d19a6f3d0528a93b60defb72be2"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ITKIOWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85525b61f34607523764cee36c6077fbb6215b8b"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "8b4ef778c836e8ee202d2bb7b0f7e5c1f8ea6c06ce85e27b8bb36ae36cf78a01"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.powerpc64le-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[ITKIOWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51ea6fd26c8cc57a79bd80be0f0d1215b444f989"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "1f66051a3fbb92d0c4a6adb6f68a47353d6586889903b28eef457b27a91a517a"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.powerpc64le-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[ITKIOWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8453ab8f123838fc95e804bf68339408a00c81ed"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "c265d304407642ebc7d6b7daacfc2b4c1699e2a67618ade9b3815ed82474742b"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.powerpc64le-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
git-tree-sha1 = "922c17147ec31cf0358bc6c7969bf0ebe4d4d36d"
julia_version = "1.10.0"
os = "macos"

    [[ITKIOWrapper.download]]
    sha256 = "1ba5a4c566686b790ba7339c497bf180ba573a261a64607cdc8dc78e635efb69"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
git-tree-sha1 = "997fbb6d49afb21e883ba0c93775ecc6ec89db79"
julia_version = "1.11.1"
os = "macos"

    [[ITKIOWrapper.download]]
    sha256 = "8d0fbbcf595f3ab90c2a60f9f4a531095977b236e7bb854b47b1ec6ef54a3cf8"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
git-tree-sha1 = "7d92304a84cad825d024f5e4b0afb61cc12ae3f3"
julia_version = "1.12.0"
os = "macos"

    [[ITKIOWrapper.download]]
    sha256 = "09d68611be2275db555c49b86ef624afdf09a0922cf8e336ecfd19e9da27aae0"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
git-tree-sha1 = "dc4231032c8dad1e597b2575f9b5648bafa0e820"
julia_version = "1.13.0"
os = "macos"

    [[ITKIOWrapper.download]]
    sha256 = "a1c991817993ce7f9d486f141b61323bddb9b38dccff6c15c3aac53dd0c7ae61"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7136130bc8920d72f54147dbe94bc035c1a69d31"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "158b0309c7013b37a61d94632e91fda6aa3739e8f52c3ebdf68f83b0256657b8"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8cf4474b42c281913ac80cccd77538ef9d4687f"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "33f4c356f1432f89c5478921c6a99fadda29bbe6c4d84abda10d4bb717df06bc"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6230ba3fbe8cf044d9ee70a2fa996ce157d7b0ce"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "f8184746d932deb06821cab212fde30a8705bf304a38d6b9004340157ede7ac9"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-linux-gnu-cxx03-julia_version+1.12.0.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc208480c1feefa4de71185ebbefaee721b43a26"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "bdbe16ef5ee02a9ede95917ba70d732a2b96ea40344de9810a4ff743e2a988e9"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-linux-gnu-cxx03-julia_version+1.13.0.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b9499b0d6afe5fbbe2a18c75b29b6154dcf4ad1"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "6d5d7753bf7b630a3696a365f93b3e5b6bf05ef538eed2ad98dcaa4534e03ea5"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85ef41fd467b15db1e292f6e81e0889b4cdb06f2"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "f5cc4d7095cc9675dba5fe60d62d782fbe17ca9a87348bfc7df48cb7642fcec6"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6fe627b4e6a523eec83b623350ff8fa23829273"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "fac5017075b3caceb1831089b5c7a01e50732ef7cd845c93f0f270d38d25dcb7"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[ITKIOWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "699b327cfb44628365a8c6e73a3058921a149ba8"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[ITKIOWrapper.download]]
    sha256 = "bf1cc39a789f5f61b7f319a3af1b5983bdce0331401b951d260c70f607d9ad20"
    url = "https://github.com/JuliaBinaryWrappers/ITKIOWrapper_jll.jl/releases/download/ITKIOWrapper-v2.0.0+0/ITKIOWrapper.v2.0.0.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
